### PR TITLE
Add `User.AddEmail`, implement CouchDB updates

### PR DESCRIPTION
**Pull request by mmalecki**
Re-get on save conflict.
Add `ConflictError` error.

cc @AvianFlu

### CODE REVIEW

**Comment by AvianFlu** [comment]
LGTM

**Comment by mmalecki** [comment]
As per @yawnt's suggestion we should also limit number of retries.

**Comment by mmalecki** [comment]
I'm also worried about the automatic re-get on update conflict behavior because it implicitly throws non-saved data out.

**Comment by AvianFlu** [comment]
It's a shame there's no such thing as a database that guarantees atomic updates.

**Comment by mmalecki** [comment]
@AvianFlu can you propose one we could switch to? TBH we're actually handling mostly structured data.

**Comment by AvianFlu** [comment]
Yeah, as I keep trolling, our data is definitely relational.

Postgres is probably the smarter choice, as it has some security shit and CTEs.  MySql is stupid easy to use, on the other hand.

Better question: which has the better Go libs? We may not need CTEs, so if mysql has better support, let's do that.

Needs some research.

**Comment by AvianFlu** [comment]
After some discussion, the consensus seems to be around using Postgres.

I'm gonna mess with this tonight a little.  If it gets really complicated, we'll punt that change until after the MVP.

I'll open a separate issue for this in the meantime.

**Comment by AvianFlu** [comment]
Superseded cause postgres

**Pull request closed without merging**
